// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxpahe5RbdF2N_rUnbG0Zpxc3SStWf8FI',
    appId: '1:1030431181846:web:b0a35ecd278b440b82f937',
    messagingSenderId: '1030431181846',
    projectId: 'meal-aware',
    authDomain: 'meal-aware.firebaseapp.com',
    storageBucket: 'meal-aware.appspot.com',
    measurementId: 'G-Y2VX571868',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoX6oLrX2YGgiQ5dM97C8QTcvrXztB6xI',
    appId: '1:1030431181846:android:1abf8e60e1f6e79782f937',
    messagingSenderId: '1030431181846',
    projectId: 'meal-aware',
    storageBucket: 'meal-aware.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-G1CniF8H5Lu2OHERZqASciJzszD9QAw',
    appId: '1:1030431181846:ios:2e97ff821149404982f937',
    messagingSenderId: '1030431181846',
    projectId: 'meal-aware',
    storageBucket: 'meal-aware.appspot.com',
    iosClientId: '1030431181846-nagqu4ifioi7pmcuorrugu1ar6iot9uh.apps.googleusercontent.com',
    iosBundleId: 'com.example.mealAware',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-G1CniF8H5Lu2OHERZqASciJzszD9QAw',
    appId: '1:1030431181846:ios:2e97ff821149404982f937',
    messagingSenderId: '1030431181846',
    projectId: 'meal-aware',
    storageBucket: 'meal-aware.appspot.com',
    iosClientId: '1030431181846-nagqu4ifioi7pmcuorrugu1ar6iot9uh.apps.googleusercontent.com',
    iosBundleId: 'com.example.mealAware',
  );
}
